name: Go Build & Release

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup zip
      run: sudo apt -y install zip unzip

    - name: Make bin dir
      run: mkdir ./bin

    - name: Build Linux
      run: |
        go build -v .
        tar -czvf SATE-linux.tar.gz SATE ./data ./logs
        mkdir ./bin/linux && mv SATE-linux.tar.gz ./bin/linux

    - name: Build Windows
      run: |
        env GOOS=windows GOARCH=amd64 go build -v .
        zip -r SATE-win64.zip SATE.exe ./data ./logs
        mkdir ./bin/win64 && mv SATE-win64.zip ./bin/win64

    - name: Test
      run: go test -v .
