name: Go Build & Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup zip
      run: sudo apt -y install zip unzip

    - name: Build Linux
      run: |
        go build -v .

    - name: Build Windows
      run: |
        env GOOS=windows GOARCH=amd64 go build -v .

    - name: Archive Releases
      run: |
        tar -czvf SATE-linux.tar.gz SATE ./data ./logs
        zip -r SATE-win64.zip SATE.exe ./data ./logs

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "SATE"
        files: |
          *.zip
          *.tar.gz