name: Go Build & Release

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup zip
      run: sudo apt -y install zip unzip

    - name: Make bin dir
      run: mkdir ./bin

    - name: Build Linux
      run: |
        go build -v .
        tar -czvf SATE-linux.tar.gz SATE ./data ./logs
        mv SATE-linux.tar.gz ./bin

    - name: Build Windows
      run: |
        env GOOS=windows GOARCH=amd64 go build -v .
        zip -r SATE-win64.zip SATE.exe ./data ./logs
        mv SATE-win64.zip ./bin

#    - name: Commit Releases
#      run: |
#        git config --global user.name 'Josh Schmille'
#        git config --global user.email 'josh.schmille@gmail.com'
#        git add --all
#        git commit -m "New Release"

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: New Release
        author_email: josh.schmille@gmail.com
        author_name: Josh Schmille