name: Go Build & Release

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup zip
      run: sudo apt -y install zip unzip

    - name: Build Linux
      run: |
        go build -v .
        tar -czvf SATE-linux.tar.gz SATE ./data ./logs
        mv SATE-linux.tar.gz ./bin/linux

    - name: Build Windows
      run: |
        env GOOS=windows GOARCH=amd64 go build -v .
        zip -r SATE-win64.zip SATE.exe ./data ./logs
        mv SATE-win64.zip ./bin/win64

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release Test"
          files: |
            *.zip
            *.tar.gz

    - name: Test
      run: go test -v .